import ('SimpleLUI', 'SimpleLUI.API.Core')
import ('SimpleLUI', 'SimpleLUI.API.Core.Math')
import ('SimpleLUI', 'SimpleLUI.API.Core.Extras')

-- Auto Generated by SLUI 'Unity's UI to Lua Converter'
-- Time 21.08.2019 18:11:58

-- ![Definition]
-- Panel(RectTransform)
local obj_23196 = core:Create('Panel')
-- Panel(Image)
local obj_23196__23200 = obj_23196:AddComponent('Image')
-- Panel(JEMInterfaceFadeElement)
local obj_23196__28256 = obj_23196:AddComponent('SLUIJEMFadeElement')
-- Panel(JEMInterfaceFadeAnimation)
local obj_23196__28258 = obj_23196:AddComponent('SLUIJEMFadeAnimation')
-- Image (0)(RectTransform)
local obj_21696 = core:Create('Image (0)')
-- Image (0)(Image)
local obj_21696__21702 = obj_21696:AddComponent('Image')
-- Image (0)(JEMInterfaceFadeElement)
local obj_21696__29286 = obj_21696:AddComponent('SLUIJEMFadeElement')
-- Image (1)(RectTransform)
local obj_21670 = core:Create('Image (1)')
-- Image (1)(Image)
local obj_21670__21682 = obj_21670:AddComponent('Image')
-- Image (1)(JEMInterfaceFadeElement)
local obj_21670__29282 = obj_21670:AddComponent('SLUIJEMFadeElement')
-- Image (2)(RectTransform)
local obj_21716 = core:Create('Image (2)')
-- Image (2)(Image)
local obj_21716__21698 = obj_21716:AddComponent('Image')
-- Image (2)(JEMInterfaceFadeElement)
local obj_21716__29290 = obj_21716:AddComponent('SLUIJEMFadeElement')
-- Image (3)(RectTransform)
local obj_21688 = core:Create('Image (3)')
-- Image (3)(Image)
local obj_21688__21714 = obj_21688:AddComponent('Image')
-- Image (3)(JEMInterfaceFadeElement)
local obj_21688__29284 = obj_21688:AddComponent('SLUIJEMFadeElement')
-- Image (4)(RectTransform)
local obj_24250 = core:Create('Image (4)')
-- Image (4)(Image)
local obj_24250__24254 = obj_24250:AddComponent('Image')
-- Image (4)(JEMInterfaceFadeElement)
local obj_24250__29288 = obj_24250:AddComponent('SLUIJEMFadeElement')
-- Header(RectTransform)
local obj_21664 = core:Create('Header')
-- Header(Image)
local obj_21664__21660 = obj_21664:AddComponent('Image')
-- Header(JEMInterfaceFadeElement)
local obj_21664__21662 = obj_21664:AddComponent('SLUIJEMFadeElement')
-- Text(RectTransform)
local obj_21728 = core:Create('Text')
-- Text(Text)
local obj_21728__21690 = obj_21728:AddComponent('Text')
-- Text(JEMInterfaceFadeElement)
local obj_21728__21718 = obj_21728:AddComponent('SLUIJEMFadeElement')
-- Button(RectTransform)
local obj_21656 = core:Create('Button')
-- Button(Image)
local obj_21656__21730 = obj_21656:AddComponent('Image')
-- Button(Button)
local obj_21656__21720 = obj_21656:AddComponent('Button')
-- Button(JEMInterfaceFadeElement)
local obj_21656__21734 = obj_21656:AddComponent('SLUIJEMFadeElement')
-- Text(RectTransform)
local obj_21666 = core:Create('Text')
-- Text(Text)
local obj_21666__21732 = obj_21666:AddComponent('Text')
-- Text(JEMInterfaceFadeElement)
local obj_21666__21652 = obj_21666:AddComponent('SLUIJEMFadeElement')

-- ![DefinitionExtras]
-- Panel(RectTransform)
obj_23196.rectTransform.anchor = 'Stretch'
-- Image (0)(RectTransform)
obj_21696.rectTransform:SetParent(obj_23196.rectTransform)
obj_21696.rectTransform.anchor = 'Middle'
-- Image (1)(RectTransform)
obj_21670.rectTransform:SetParent(obj_23196.rectTransform)
obj_21670.rectTransform.anchor = 'Middle'
-- Image (2)(RectTransform)
obj_21716.rectTransform:SetParent(obj_23196.rectTransform)
obj_21716.rectTransform.anchor = 'Middle'
-- Image (3)(RectTransform)
obj_21688.rectTransform:SetParent(obj_23196.rectTransform)
obj_21688.rectTransform.anchor = 'Middle'
-- Image (4)(RectTransform)
obj_24250.rectTransform:SetParent(obj_23196.rectTransform)
obj_24250.rectTransform.anchor = 'Bottom'
-- Header(RectTransform)
obj_21664.rectTransform:SetParent(obj_23196.rectTransform)
obj_21664.rectTransform.anchor = 'StretchTop'
-- Text(RectTransform)
obj_21728.rectTransform:SetParent(obj_21664.rectTransform)
obj_21728.rectTransform.anchor = 'Stretch'
-- Button(RectTransform)
obj_21656.rectTransform:SetParent(obj_21664.rectTransform)
obj_21656.rectTransform.anchor = 'MiddleRight'
-- Text(RectTransform)
obj_21666.rectTransform:SetParent(obj_21656.rectTransform)
obj_21666.rectTransform.anchor = 'Stretch'

-- ![Property]
-- Panel(RectTransform)
obj_23196:SetActive(false)
obj_23196.rectTransform.anchoredPosition = SLUIVector2(0, 0)
obj_23196.rectTransform.sizeDelta = SLUIVector2(0, 0)
-- Panel(Image)
obj_23196__23200.imageType = 'Sliced'
obj_23196__23200.color = SLUIColor(0, 0, 0, 0.6)
-- Panel(JEMInterfaceFadeAnimation)
obj_23196__28258.animationSpeed = 16
obj_23196__28258.animationEnterScale = 1.06
obj_23196__28258.animationExitScale = 1.03
-- Image (0)(RectTransform)
obj_21696.rectTransform.anchoredPosition = SLUIVector2(-456.9, -6.3)
obj_21696.rectTransform.sizeDelta = SLUIVector2(149.53, 240.81)
-- Image (0)(Image)
obj_21696__21702.imageType = 'Simple'
obj_21696__21702.preserveAspect = true
obj_21696__21702.sprite = 'auto_res//puti1.png'
-- Image (1)(RectTransform)
obj_21670.rectTransform.anchoredPosition = SLUIVector2(-294.7, -6.3)
obj_21670.rectTransform.sizeDelta = SLUIVector2(149.53, 240.81)
-- Image (1)(Image)
obj_21670__21682.imageType = 'Simple'
obj_21670__21682.preserveAspect = true
obj_21670__21682.sprite = 'auto_res//puti1.png'
-- Image (2)(RectTransform)
obj_21716.rectTransform.anchoredPosition = SLUIVector2(-43.22002, -6.3)
obj_21716.rectTransform.sizeDelta = SLUIVector2(149.53, 240.81)
-- Image (2)(Image)
obj_21716__21698.imageType = 'Simple'
obj_21716__21698.preserveAspect = true
obj_21716__21698.sprite = 'auto_res//puti2.png'
-- Image (3)(RectTransform)
obj_21688.rectTransform.anchoredPosition = SLUIVector2(420.1, -6.3)
obj_21688.rectTransform.sizeDelta = SLUIVector2(149.53, 240.81)
-- Image (3)(Image)
obj_21688__21714.imageType = 'Simple'
obj_21688__21714.preserveAspect = true
obj_21688__21714.sprite = 'auto_res//puti3.png'
-- Image (4)(RectTransform)
obj_24250.rectTransform.anchoredPosition = SLUIVector2(0, 29.55)
obj_24250.rectTransform.sizeDelta = SLUIVector2(149.5, 33.9)
-- Image (4)(Image)
obj_24250__24254.imageType = 'Simple'
obj_24250__24254.preserveAspect = true
obj_24250__24254.sprite = 'auto_res//sztos2.png'
-- Header(RectTransform)
obj_21664.rectTransform.anchoredPosition = SLUIVector2(0, -70.34)
obj_21664.rectTransform.sizeDelta = SLUIVector2(-60, 86.79999)
-- Header(Image)
obj_21664__21660.imageType = 'Sliced'
obj_21664__21660.color = SLUIColor(0.1037736, 0.1037736, 0.1037736, 0.8392157)
obj_21664__21660.sprite = 'auto_res//Background.png'
-- Text(RectTransform)
obj_21728.rectTransform.anchoredPosition = SLUIVector2(-122, 0)
obj_21728.rectTransform.sizeDelta = SLUIVector2(-343.9, -30)
-- Text(Text)
obj_21728__21690.text = "YOU ARE DEAD!"
obj_21728__21690.alignment = 'MiddleLeft'
obj_21728__21690.resizeTextForBestFit = true
obj_21728__21690.color = SLUIColor(0.9, 0.9, 0.9, 1)
-- Button(RectTransform)
obj_21656.rectTransform.anchoredPosition = SLUIVector2(-151.5, 2.4796E-05)
obj_21656.rectTransform.sizeDelta = SLUIVector2(213, 56.8)
-- Button(Image)
obj_21656__21730.imageType = 'Sliced'
obj_21656__21730.color = SLUIColor(0.108297, 0.573, 0.3049599, 1)
obj_21656__21730.sprite = 'auto_res//UISprite.png'
-- Button(Button)
obj_21656__21720.targetGraphic = obj_21656__21730
obj_21656__21720.normalColor = SLUIColor(1, 1, 1, 1)
obj_21656__21720.highlightedColor = SLUIColor(0.769, 0.769, 0.769, 1)
obj_21656__21720.pressedColor = SLUIColor(0.6569999, 0.6569999, 0.6569999, 1)
obj_21656__21720.selectedColor = SLUIColor(0.9607843, 0.9607843, 0.9607843, 1)
obj_21656__21720.disabledColor = SLUIColor(0.7843137, 0.7843137, 0.7843137, 0.5019608)
-- Text(RectTransform)
obj_21666.rectTransform.anchoredPosition = SLUIVector2(0, 0)
obj_21666.rectTransform.sizeDelta = SLUIVector2(0, 0)
-- Text(Text)
obj_21666__21732.text = "RESPAWN!!!"
obj_21666__21732.alignment = 'MiddleCenter'
obj_21666__21732.resizeTextForBestFit = true
obj_21666__21732.resizeTextMaxSize = 28
obj_21666__21732.color = SLUIColor(0.909, 0.909, 0.909, 1)

-- ![Extras]
